{
  "comments": [
    {
      "key": {
        "uuid": "d8093af4_a63d03c9",
        "filename": "platform/api/udp_socket.cc",
        "patchSetId": 1
      },
      "lineNbr": 29,
      "author": {
        "id": 1336186
      },
      "writtenOn": "2019-08-19T21:16:08Z",
      "side": 1,
      "message": "kAgain is an error as well, I\u0027m not sure we should close the socket automatically when an error happens.",
      "range": {
        "startLine": 27,
        "startChar": 2,
        "endLine": 29,
        "endChar": 3
      },
      "revId": "694ef1cda08c5a808a265d3c244213111e94aeff",
      "serverId": "3ce6091f-6c88-37e8-8c75-72f92ae8dfba",
      "unresolved": true
    },
    {
      "key": {
        "uuid": "5ecf4c89_98ecf81b",
        "filename": "platform/api/udp_socket.h",
        "patchSetId": 1
      },
      "lineNbr": 165,
      "author": {
        "id": 1336186
      },
      "writtenOn": "2019-08-19T21:16:08Z",
      "side": 1,
      "message": "Any other states? I.e. socket is created but not yet bound.",
      "range": {
        "startLine": 165,
        "startChar": 2,
        "endLine": 165,
        "endChar": 37
      },
      "revId": "694ef1cda08c5a808a265d3c244213111e94aeff",
      "serverId": "3ce6091f-6c88-37e8-8c75-72f92ae8dfba",
      "unresolved": true
    }
  ]
}