{
  "comments": [
    {
      "key": {
        "uuid": "e43714d8_b11d5ff8",
        "filename": "base/error.h",
        "patchSetId": 11
      },
      "lineNbr": 29,
      "author": {
        "id": 1215804
      },
      "writtenOn": "2018-10-01T18:50:04Z",
      "side": 1,
      "message": "I\u0027m curious why this was added, since we ban exceptions and use -fno-exceptions.",
      "range": {
        "startLine": 29,
        "startChar": 23,
        "endLine": 29,
        "endChar": 31
      },
      "revId": "d2e6fe6c67daf7699d623bcd749469c33e34ff39",
      "serverId": "3ce6091f-6c88-37e8-8c75-72f92ae8dfba",
      "unresolved": true
    }
  ]
}